
name: Mera Phela Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      tumhara_naam:
        description: "Apna naam likho"
        required: true
        default: "Bhai"
      environment:
        description: "Kaunsa Environment"
        required: true
        type: choice
        options:
         - development
         - staging
         - production
  schedule:
    - cron: '*/2* * * *'

jobs:
  phela-job:
    runs-on: ubuntu-latest

    steps:

      - name: Trigger check kro
        run: |
          echo "Kis cheez ne chalaya? ${{ github.event_name }} "

      - name: Namaste karo
        run: echo "Namaste ${{ github.event.inputs.tumhara_naam || 'Automatic Runner' }} "

      - name: Environment Dekho
        run: echo "Chal rahe hain ${{ github.event.inputs.environment || 'scheduled run' }} "

      - name: System info dekho
        run: |
            echo "Date: $(date)"
            echo "OS: $(uname -a)"

